Create NexClipper-Agent examples
dcos/examples pull request #383
Opened 2018-11-12 07:00 UTC by ssipflow

Create example for nexclipper-agent

2018-11-26 15:04 UTC, mattj-io requested changes
Hi, thanks for your example ! I made some suggestions inline to hopefully make the text a bit clearer, please check my suggestions and push the changes.

2018-11-26 15:04 UTC, mattj-io commented on nexclipper-agent/1.10/README.md
> +[NexClipper][nexclipper] is the container monitoring and performance management service specialized in Docker, Apache Mesos, Marathon, DC/OS, Mesosphere, Kubernetes. In this beta version, it support
is a container monitoring and performance management service for Docker, Apache Mesos, Marathon, DC/OS, Mesosphere, Kubernetes. In this beta version, it supports monitoring and analysis of the container cluster (Mesos, DC/OS, Mesosphere, Kubernetes), Container, Agent, event management, resource tracing, performance monitor and basic root cause functionality for event management with SaaS version. Future versions will provide rich functionality for root cause (event management, resource tracing, performance monitor and transaction tasing, etc) soon.

2018-11-26 15:04 UTC, mattj-io commented on nexclipper-agent/1.10/README.md
> +3. Set the agnet-key you downloaded
agent key

2018-11-29 01:37 UTC, ssipflow commented
Thank you for your suggestion.!!

2019-12-22 16:36 UTC, closed without merging